### ISSUE TITLE
make errors on CentOS 6.5

### ISSUE THREAD

**Issue by tvaccari** [madrisan/nagios-plugins-linux#1]
Having some issues getting the plugins to compile on CentOS 6.5.

$ git clone https://github.com/madrisan/nagios-plugins-linux.git
$ autoreconf --install
$ ./configure 

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a pax tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for an ANSI C-conforming const... yes
checking for function prototypes... yes
checking for inline... inline
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking whether compiler accepts -Wall... yes
checking whether compiler accepts -Wformat... yes
checking whether compiler accepts -Wformat-security... yes
checking whether compiler accepts -Wmissing-noreturn... yes
checking whether compiler accepts -Wmissing-format-attribute... yes
checking whether compiler accepts -Wredundant-decls... yes
checking whether compiler accepts -Wshadow... yes
checking whether compiler accepts -Wsign-compare... yes
checking whether compiler accepts -Wstrict-aliasing=2... yes
checking whether compiler accepts -Wunused... yes
checking whether compiler supports __attribute__((__alloc_size__ args))... yes
checking whether compiler supports __attribute__((__malloc__))... yes
checking whether compiler supports the noreturn feature... using __attribute__
checking whether compiler supports __attribute__((__format__ (__printf__, x,y))... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking linux/if_link.h usability... no
checking linux/if_link.h presence... yes
configure: WARNING: linux/if_link.h: present but cannot be compiled
configure: WARNING: linux/if_link.h:     check for missing prerequisite headers?
configure: WARNING: linux/if_link.h: see the Autoconf documentation
configure: WARNING: linux/if_link.h:     section "Present But Cannot Be Compiled"
configure: WARNING: linux/if_link.h: proceeding with the preprocessor's result
configure: WARNING: linux/if_link.h: in the future, the compiler will take precedence
configure: WARNING:     ## ---------------------------------------- ##
configure: WARNING:     ## Report this to davide.madrisan@gmail.com ##
configure: WARNING:     ## ---------------------------------------- ##
checking for linux/if_link.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking mntent.h usability... yes
checking mntent.h presence... yes
checking for mntent.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/mount.h usability... yes
checking sys/mount.h presence... yes
checking for sys/mount.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/sysctl.h usability... yes
checking sys/sysctl.h presence... yes
checking for sys/sysctl.h... yes
checking sys/sysinfo.h usability... yes
checking sys/sysinfo.h presence... yes
checking for sys/sysinfo.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/swap.h usability... yes
checking sys/swap.h presence... yes
checking for sys/swap.h... yes
checking utmpx.h usability... yes
checking utmpx.h presence... yes
checking for utmpx.h... yes
checking for asprintf... yes
checking for clock_gettime in -lrt... yes
checking for clock_gettime with clock CLOCK_MONOTONIC... yes
checking for getmntent... yes
checking for hasmntopt... yes
checking for memset... yes
checking for regcomp... yes
checking for socket... yes
checking for strchr... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
checking for strtoull... yes
checking for sysinfo... yes
checking for uname... yes
checking for library containing getmntent... none required
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for working strtod... yes
checking for cpu_set_t... yes
checking whether CPU_ALLOC is declared... yes
checking for /proc/meminfo... found /proc/meminfo
checking for get_nprocs_conf... yes
checking for get_nprocs... yes
checking for getloadavg... yes
checking for struct sockaddr_in6... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uid_t in sys/types.h... yes
checking for ranlib... ranlib
checking whether ln -s works... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating lib/Makefile
config.status: creating plugins/Makefile
config.status: creating config.h
config.status: executing depfiles commands

$ make

make --no-print-directory all-recursive
Making all in include
make[2]: *** No rule to make target `kernelver.h', needed by `all-am'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by madrisan** [comment]
Hello,
sorry for the _looong_ delay...
This problem should have been fixed meanwhile as RHEL6 is one of my building and testing environment.

Please let me known.
