### ISSUE TITLE
check_cpufreq uses invalid units in perfdata

### ISSUE THREAD

**Issue by sbraz** [madrisan/nagios-plugins-linux#11]
Hi,
According to https://nagios-plugins.org/doc/guidelines.html
>  UOM (unit of measurement) is one of:
>    no unit specified - assume a number (int or float) of things (eg, users, processes, load averages)
 >   s - seconds (also us, ms)
>    % - percentage
 >   B - bytes (also KB, MB, TB)
>    c - a continous counter (such as bytes transmitted on an interface)

This causes Icinga to drop the perfdata:
```
warning/InfluxdbWriter: Ignoring invalid perfdata value: cpu0_freq=4700000Hz;;;800000;5000000
```

Could you please remove the unit from the perfdata output?

**Comment by madrisan** [comment]
Thanks for the bug report!
This issue has been addressed by the PR #13
