### ISSUE TITLE
check_cpufreq returns Khz, not Hz

### ISSUE THREAD

**Issue by sbraz** [madrisan/nagios-plugins-linux#12]
Hi,
The value returned from /sys is not in Hz but in Khz so you need to multiply it by 1000 after getting it:
https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt
> scaling_cur_freq :		Current frequency of the CPU as determined by
>				the governor and cpufreq core, in KHz. This is
>				the frequency the kernel thinks the CPU runs
>				at.

**Comment by madrisan** [comment]
Reporting values in kHz seems fine to me.
As you noted this is the unit of the kernel counters.

**Comment by sbraz** [comment]
I doubt that most perfdata processing tools can handle Mhz/Khz, all nagios checks tend to use the base unit for perfdata and it is the processing tool's job to convert to multiple of the base unit.
I'm using grafana and it doesn't understand Khz or Mhz, just plain Hz:
https://github.com/grafana/grafana/blob/a7d4e6caa37269c25462f3f226860e7abb2ea1e3/public/app/core/utils/kbn.ts#L962

**Comment by madrisan** [comment]
Ok. Thanks again.
I think I'll add a command-line switch to permit the user to the unit.

**Comment by madrisan** [comment]
And if you like this project, do not forget to add a star in the project homepage ;)

**Comment by madrisan** [comment]
Now it's possible to get the values in Hz by using the command-line option `-H'.
