### ISSUE TITLE
[Bug] Build does not fail when --enable-libvarlink is passed and libvarlink is unavailable

### ISSUE THREAD

**Issue by sbraz** [madrisan/nagios-plugins-linux#124]
# 🐛 Bug
## Describe the bug
Hi Davide,
I didn't understand why `check_podman` wasn't getting built when I passed `--enable-libvarlink`. I eventually realised that I didn't have libvarlink installed.

## How to reproduce
Steps to reproduce the behaviour:
* build with `--enable-libvarlink` on a system without libvarlink
* no error occurs but `check_podman` is not built

## Expected behaviour
There should be an error because libvarlink is not available, this should not be silently ignored because we purposely requested libvarlink support. 

## Additional context
 - Linux distribution: Gentoo
 - Version: git master
 - I assume `--enable-libcurl` has the same problem but I did not test on a system without libcurl installed

**Comment by madrisan** [comment]
Thanks for the report. I will test both the setup.
`check_podman` should be rewritten from scratch because nowadays it doesn't use` varlink` anymore.
Are you planning to use it or was just a build test? Just curious.

**Comment by sbraz** [comment]
>  Are you planning to use it or was just a build test? Just curious.

I just made everything built successfully with the latest release before bumping the Gentoo package and I noticed this weird behaviour. I'm afraid I only use your `check_memory` :smile:
