### ISSUE TITLE
[Bug] check_network: failed to bind netlink socket (Address already in use)

### ISSUE THREAD

**Issue by nE0sIghT** [madrisan/nagios-plugins-linux#126]
Hello! Thanks for your great plugins

# 🐛 Bug
## Describe the bug
We are using `check_network` plugin in dockerized icinga containers.  
Containers are running with host network.  
Some checks are failing with the `check_network: failed to bind netlink socket (Address already in use)` error and `unknown` status.  
This happens about one time in 1-7 days per server.

## How to reproduce
Sadly I have no exact steps to reproduce this issue

1. We are using `icinga/icinga2` public docker image as our base.  
2. Plugins are built using `debian:bullseye-slim` builder:
```dockerfile
RUN cd /madrisan-nagios-plugins-linux ;\
	mkdir dist ;\
	autoreconf -fi ;\
	./configure --libexecdir=/usr/lib/nagios/plugins/madrisan ;\
	make ;\
	make install "DESTDIR=$(pwd)/dist" ;\
	install -m 644 -D contrib/icinga2/CheckCommands.conf $(pwd)/dist/usr/share/icinga2/include/plugins-contrib.d/madrisan.conf
```
3. `check_network` is executed with 2 service options:
```
madrisan-network_ifname: ^(eth\|en\|lan).*
madrisan-network_no-loopback: true
```
4. Check period is 90 seconds

## Expected behaviour
No errors

## Additional context
 - Host OSes are Debian 9 and 10
 - We are using 1d5df468c1ab22a4ddaa46339574127138e6ce81 repository commit for building plugins. As I see there are no changes in `check_network` after this commit.

Any suggestions with our problem?

**Comment by madrisan** [comment]
Of course it should be interesting to know who is using the address.
I have no clues at the moment...
