### ISSUE TITLE
[Bug] Cpu Freq doesnt work , It shows only an output with Ok

### ISSUE THREAD

**Issue by EmilioIppoliti** [madrisan/nagios-plugins-linux#129]
# 🐛 Bug
## How to reproduce
Steps to reproduce the behaviour:
1. Options passed to ./configure at build time (if applicable)
2. A way to recreate the problem
3. Command line to enter
4. The exact output printed by the plugin

## Additional context
 - Linux distribution
 - Version [e.g. 27]
 - Add any other context about the problem here.

**Comment by madrisan** [comment]
Thanks for your report.
This plugin parses the following sysfs path
```
#define PATH_SYS_SYSTEM         PATH_SYS "/devices/system/cpu"
```
usually `/sys/devices/system/cpu/`.
Which is the distribution you run the plugin on? Which version.
Is the `sysfs` filesystem mounted?
If it's the case, what is the output of the commands
```
ls -l /sys/devices/system/cpu/
find /sys/devices/system/cpu/cpu0/cpufreq/ -type f | while read f; do echo "[$f]"; cat $f; done
```
?

**Comment by madrisan** [comment]
No information provided to debug and fix the problem.
