### ISSUE TITLE
check_memory: remove comma from perfdata

### ISSUE THREAD

**Issue by ggzengel** [madrisan/nagios-plugins-linux#140]
https://github.com/madrisan/nagios-plugins-linux/blob/13424c74d17dd3f47b150441013c16e4b0caac66/plugins/check_memory.c#L265

[2024-01-29 00:00:34 +0000] warning/Influxdb2Writer: Ignoring invalid perfdata for checkable 'px1!Memory' and command 'check_memory' with value: vmem_pageouts/s=8926,

comma is not allowed in perfdata

```
'sudo' '-n' '/usr/lib/nagios/plugins/check_memory' '-a' '-c' '10%:' '-s' '-w' '20%:'
memory WARNING: 11.58% (1896848 kB) available | mem_total=16376376kB mem_used=14145580kB;;;0;16376376 mem_free=590164kB mem_shared=145776kB mem_buffers=0kB mem_cached=1640632kB mem_available=1896848kB;3275275;1637637;0;16376376 mem_active=1213304kB mem_anonpages=13969532kB mem_committed=1950832kB mem_dirty=52kB mem_inactive=14287416kB, vmem_pageins/s=0, vmem_pageouts/s=0, vmem_pgmajfault/s=6

```

**Comment by madrisan** [comment]
A long-standing, stupid bug. Thanks for the report!
