### ISSUE TITLE
Remove libtool from the git repo

### ISSUE THREAD

**Issue by sbraz** [madrisan/nagios-plugins-linux#15]
When I run `autoreconf -i`, this file gets overwritten, I doubt it needs to be versioned.

**Comment by madrisan** [comment]
You're right but I added this file and several other ones to make easier the compilation of the source code starting from a fresh copy of the git repository.

**Comment by sbraz** [comment]
I could see how this would makes sense _if `configure` were versioned too_. However you're not including it so I still have to regenerate it, therefore regenerating `libtool` as well and polluting my git tree, right?

IMO `configure` (but not `libtool`) should be included in releases (and it's already the case!). The git repository should only be used by developers who should be able to regenerate the required files themselves.

**Comment by sbraz** [comment]
Two more arguments against including libtool:
* I just fast-forwarded my tree to test the kHz/Hz commit and ran `make` without doing anything else (because there were no changes to the autotools files) but it failed with `../libtool: line 5381: /usr/bin/sed: No such file or directory` (yeah it's in /bin here).
* I can't freely move HEAD and recompile the programmes because sooner or later I'll hit `error: Your local changes to the following files would be overwritten by checkout: libtool`. This means that if I were to run a git bisect with a script that builds the checks, I'd have to make it git reset after each build… not fun!

**Comment by madrisan** [comment]
Ok. Your arguments sound rock-solid.
This issue has been addressed in https://github.com/madrisan/nagios-plugins-linux/pull/18
