### ISSUE TITLE
Improvement to check_memory include min, max, warning and critical in perfdata

### ISSUE THREAD

**Issue by sbraz** [madrisan/nagios-plugins-linux#32]
Hello,
Adding these to check_memory's perfdata would make it easier for me to process the perfdata. I'm especially interested in the max value that many tools use while making graphs from perfdata.

**Comment by madrisan** [comment]
Hello, Can you explain with more detail?
Min and max memory calculated over a period of time? Nagios plugins are stateless.
Or just the max memory available in the system (`mem_total`)?

**Comment by sbraz** [comment]
>  Or you just mean the min and max of every entry? Should be |0, mem_total]

Yes, currently if I run `check_memory -b -a -w 10: -c 5:`, the perfdata contains something like `mem_total=16725532672B mem_available=13452328960B`, it should be `mem_available=13452328960B;1672553267:;836276633:;0;25224855552` (with the warning and critical ranges obtained as percentages of `mem_total`).

**Comment by madrisan** [comment]
And 25224855552 is?

**Comment by sbraz** [comment]
Sorry it looks like I made a mistake, I fixed the example, the last value is the max: http://nagios-plugins.org/doc/guidelines.html#AEN200

**Comment by madrisan** [comment]
Ok. And also min and max should be, in your example, the 90% and 95% of the total memory (not the 10% and 5%). Right? This should be not so easy to implement, because of the different command line syntaxes that are allowed by nagios. In the next days I should found some time for checking what can be done.

**Comment by sbraz** [comment]
`min` and `max` are the minimum and maximum values that the metric can take (0 and the total amount of memory), I assume you meant the thresholds.

In my example, I was showing what the `warn` and `crit` thresholds would look like for `mem_available` so they would still be 5% and 10%. But the `mem_used` metric would show 90% and 95% thresholds.

In the end I think the metrics that really need this additional info would be `mem_used` and `mem_available`. You could even drop `mem_total` since people could rely on the max of either available or used memory. 

If I'm not making sense (it's a bit hard to describe all this), I can give you a complete example of the kind of perfdata I'd ideally be looking for.

**Comment by madrisan** [comment]
Can you check, compile and test the branch "issue_32" please.
It should implement the enhancement you asked for.

Now the output has changed as follows:

    $ ./plugins/check_memory --available -w 20%: -c 10%:
    memory OK: 73.84% (12038364 kB) available | mem_total=16302692kB mem_used=3405896kB;;;0;16302692 mem_free=8639864kB mem_shared=524152kB mem_buffers=389696kB mem_cached=3867236kB mem_available=12038364kB;3260538;1630269;0;16302692 mem_active=4340364kB mem_anonpages=3016112kB mem_committed=8950552kB mem_dirty=11936kB mem_inactive=2320924kB

and 

    $ ./plugins/check_memory -w 80% -c 90%
    memory OK: 21.34% (3479712 kB) used | mem_total=16302692kB mem_used=3479712kB;13042153;14672422;0;16302692 mem_free=8569500kB mem_shared=521368kB mem_buffers=389796kB mem_cached=3863684kB mem_available=11967332kB;;;0;16302692 mem_active=4412800kB mem_anonpages=3088352kB mem_committed=8999452kB mem_dirty=9080kB mem_inactive=2322980kB

**Comment by sbraz** [comment]
Thank you, it works fine! I was going to mention the fact that the start and end warn/crit info should be retained in perfdata (including the colon from your first example), a bit like what some of the original nagios plugins do:
```
$ /usr/lib64/nagios/plugins/check_procs -c 1:1
PROCS CRITICAL: 132 processes | procs=132;;1:1;0;
```
But apparently [this is not supported by icinga anyway](https://github.com/Icinga/icinga2/issues/909) and is results in:
```
debug/PerfdataValue: Ignoring unsupported perfdata critical range, value: '1:1'.
```

I see that you use `max(start, end)` to display as warning/critical perfdata. Maybe you could just not display it at all in complex cases (both start and end != 0) to avoid showing slightly inconsistent data (what if I want to use something like `-w 10:90` to receive an alert when too little or too much memory is used?). However, I am aware that I've already asked you to change a lot of code, so I'll understand if you want to keep it as it is.

Anyway, what I was missing the most was the min/max part so I'm fine with the new feature, thanks a lot for your work, I really appreciate it!

**Comment by madrisan** [comment]
Cool.
Yes, you're right about the usage of the max macro. I just used it to speed-up the implementation and let you check the result. I've planned to create a function for generating the perfdata with a better logic.
I'm happy to see that this project is appreciated.

**Comment by madrisan** [comment]
The changes (see [PR#35](https://github.com/madrisan/nagios-plugins-linux/pull/35)) have been pushed to the master branch.
