### ISSUE TITLE
ts_sysdockermemstat.data missing from release tarball

### ISSUE THREAD

**Issue by sbraz** [madrisan/nagios-plugins-linux#38]
Hi Davide!
I'm thinking it would be nice to package your plugins for Gentoo and so far it's going well but I noticed that `tslibcontainer_memory` fails because the data file isn't included in v24's tarball:
```
FAIL: tslibcontainer_memory
===========================

./tslibcontainer_memory: error opening /var/tmp/portage/net-analyzer/nagios-plugins-linux-madrisan-24/work/nagios-plugins-linux-24/tests/ts_sysdockermemstat.data (No such file or directory)
FAIL tslibcontainer_memory (exit status: 3)
```

Would it be possible to release a new version that includes the improved check_memory perfdata?

**Comment by madrisan** [comment]
Hi @sbraz 
nagios-plugins-linux on Gentoo? That's will be amazing!
I'll package another version as soon as I will merge and test the issue [#39](https://github.com/madrisan/nagios-plugins-linux/issues/39). Sould be in a couple of days.
If you need to merge some code for Gentoo packaging in the `packages`  folder, please let me known.

**Comment by sbraz** [comment]
Thanks! I don't think I'll need anything else. The package will be added to the Gentoo tree and I'll maintain it there. Maybe we can update the README to let users know how to install it on Gentoo.
I will have to rename 3 plugins that conflict with monitoring-plugins' ones: load, swap and users. I was going to suffix them with `_madrisan`, what do you think?

**Comment by sbraz** [comment]
Of course, I'm just waiting for the new release :)

**Comment by madrisan** [comment]
The tarballs for version 25 are now available. Can you check is all work fine for you, please?

**Comment by sbraz** [comment]
```
# TOTAL: 19                                                                                                                                                                                                        
# PASS:  19                                                                                                                                                                                                        
```

That works, thanks! Are you available on gitter? I have a few questions about the Gentoo package.
