### ISSUE TITLE
check_network set limits for warning and critical and view max capacity

### ISSUE THREAD

**Issue by iam333** [madrisan/nagios-plugins-linux#55]
Hi! thanks in advance!

It would be very interesting to establish limits for warning and critical alarms of some of the displayed values. And "basic" things like being able to show the percentage of use with respect to the maximum capacity limit of the device.

Thanks!

**Comment by madrisan** [comment]
Ok. I'll investigate a see what can be done.
Do not forgot to add a star to this project if you find it useful. ;)

**Comment by madrisan** [comment]
Unfortunately it cannot fully implemented, because some network interface types do not have a speed associated with. The wireless ones for instance. But can be done for ethernet interfaces. Some work is already done in the master branch.

**Comment by madrisan** [comment]
See PR [#57](https://github.com/madrisan/nagios-plugins-linux/pull/57).

**Comment by iam333** [comment]
Hi!!! 

First of all, congratulations on the great work done, it is a great collection of plugins!
I have been testing the new version of check_network and have drawn the following conclusions, I think the following would be very useful:

	1º - It should be possible to establish the parameters of limits for warning and critical, as it happens with other plugins, and if it could be with percentages it would be optimal, for example -w 80 -c 90 (warning reaching 80 and critical at 90% of the maximum capacity)

	2º - I did not finish seeing the option that I requested in the thread, or perhaps I did not explain myself well. I am looking for a plugin, which can notify me when a threshold (percentage with respect to the maximum) of the network card bandwidth is reached.

	3º - The plugin returns a multitude of card values, which for perfdata can be useful, but to locate an error quickly, it is a bit complicated. Would it be possible to limit the displayed values?

		`_network OK | lo_txpck / s = 2 lo_rxpck / s = 2 lo_txbyte / s = 168 ;;; 0 lo_rxbyte / s = 168 ;;; 0 lo_txerr / s = 0 lo_rxerr / s = 0 lo_txdrop / s = 0 lo_rxdrop / s = 0 lo_mcast / s = 0 lo_coll / s = 0eth2_txpck / s = 0 eth2_rxpck / s = 0 eth2_txbyte / s = 0 ;;; 0; 125000000 eth2_rxbyte / s = 0 ;;; 0; 125000000 eth2_txerr / s = 0 eth2_rxerr / s = 0 eth2_t / s = 0 eth2_rxdrop / s = 0 eth2_mcast / s = 0 eth2_coll / s = 0eth1_txpck / s = 0 eth1_rxpck / s = 1 eth1_txbyte / s = 0 ;;; 0; 125000000 eth1_rxbyte / s = 60 ;;; 0; 125000000 eth1_txerr / s = 0 eth1_rxerr / s = 0 eth1_txdrop / s = 0 eth1_rxdrop / s = 0 eth1_mcast / s = 0 eth1_coll / s = 0_`

	4º - Could help show the default values ​​established for the Warning and critical thresholds? I don't know when an alarm goes off.	

Thank U SOOOO much!!!

**Comment by madrisan** [comment]
Hello,

all the points should now be addressed in the master branch.
For the last point note that there are no default values for the thresholds. Or if you prefer, the default value is no value.

**Comment by iam333** [comment]
Hello!!
Thank you very much in advance!

I've been testing the plugin (check_network) and I've seen a little problem: If you set the output to percentage (-%) mode, the values that are set for Warning and critical should be in percentage mode as well, and I think that's not the case. .
In the following example, I have put warning at 1% and critical at 30% and as you will see, it is at 0.00% and it is giving a critical, so I understand that it is taking the value of critical as absolute value and not percentage.

`check_network -i eth1 -% --tx-only -w 1 -c 30`
`network CRITICAL - found 1 interface(s) (eth1) | eth1_txbyte/s=0.00%;;;0;100.0 eth1_rxbyte/s=0.00%;;;0;100.0 eth1_txerr/s=0 eth1_rxerr/s=0 eth1_txdrop/s=0 eth1_rxdrop/s=0 eth1_rxpck/s=1 eth1_txpck/s=1 eth1_coll/s=0 eth1_mcast/s=0`

Thanks!!!!

**Comment by madrisan** [comment]
Thanks for your bug reports.
the bug should be now fixed in the master branch:
https://github.com/madrisan/nagios-plugins-linux/commit/3f07ce7a4abb64c27880c6093eddd72fbc8d6829

It was introduced during a recent code refactoring.
