### ISSUE TITLE
[Feature Request] Ready to use packages or binaries

### ISSUE THREAD

**Issue by trickert76** [madrisan/nagios-plugins-linux#75]
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe.

If I want to use the plugins, I need to install them on productive machines. But I don't want to compile the package on them to install it per machine. So - it would be a good idea to have at least a binary file per check (Zip, Tarball, whatever). 

## Describe the solution you'd like

Because you already use Github Actions, I think it can't be so complicated to push back the created binaries to Github Packages.

## Describe alternatives you've considered

Find a maintainer per distro.

## Additional context

N/A

**Comment by madrisan** [comment]
Thank for your feature request!
The creation of the packages is already supported for several Linux distributions. It just requires docker or podman.
This feature is documented [here](https://github.com/madrisan/nagios-plugins-linux#alpine-centosrhel-debian-and-fedora-packages).
Which OS would like to be supported?
I still do not checked deeply the GitHub Actions but yes, it can be interesting. The problem are the library dependencies which are by design just a few but distro dependant.

**Comment by trickert76** [comment]
Hi @madrisan,

thanks for your answer. The creation of the packages is already supported - yes, but I need to do it by myself? Why should I? the result DEB/RPM/... is always the same.

I need it for Debian Buster.

And yes - it should be possible with Github Action to create the "artefacts". I'm not sure, but as far as I understand, Github Action has problems with container in containers (I will have a look too). Is it possible to just use a default gcc environment and then run that and create the packages without docker/podman? Otherwise have a look at: https://github.com/marketplace/actions/docker-run-action

**Comment by trickert76** [comment]
Ah, damn - the Github page is not what it was... Earlier there was a tab that shows the release files. Now it's only on the start page on the right side. https://github.com/madrisan/nagios-plugins-linux/releases/tag/v28  Okay, that helps.

I found it, as a I looked for a way to find my Github Action Uploads in my fork... This is what I did till now:

     ....
      - id: make
        run: |
          make
          make check
          make distcheck
          echo "PACKAGE_NAME=nagios-plugins-linux-$(awk '/^ID=/' /etc/*-release | sed 's/ID=//')" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: nagios-plugins-linux-*

This uploads the nagiois-plugins-linux "somewhere". I'm not sure, if this is a good solution. The version number is not easy to extract.

**Comment by trickert76** [comment]
Ah, funny, that is only the source code at the release side. The artefacts in upload-artefacts are stored on the Github run itself. You can download per Run. Ok, thats not, what it should be... buuuut

    ....
      - id: make
        run: |
          make
          make check
          make distcheck
          mv nagios-plugins-linux-*.bz2 nagios-plugins-linux-v29-$(awk '/^ID=/' /etc/*-release | sed 's/ID=//' | sed 's/"//' ).tar.bz2
 
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "nagios-plugins-linux-*.bz2"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          tag: v29

That works. I Be aware - the tag is hardcoded as I don't understand, how I can read it from the configure File. But I've -at least - https://github.com/trickert76/nagios-plugins-linux/releases/tag/v29 there are binaries...

The v29 was just a test. I think it will work on an existing release to....

**Comment by trickert76** [comment]
grmpf - no - I don't understand, why a "make" is not generating binaries.... sorry. This is a problem in your build process. I would expect that make will generate the binaries somewhere.

**Comment by madrisan** [comment]
Thanks for your tests.
A make in the available source tarball is sufficient, but not a make in the cloned repository.
As the [installation instruction](https://github.com/madrisan/nagios-plugins-linux#installation) states you have to run
```
autoreconf --install
./configure --libexecdir=/usr/lib/nagios/plugins
make
```
Does this solve the problem you're seeing?

**Comment by madrisan** [comment]
I forgot to say that you can simply run a
```
debuild -us -uc
```
command to build the Debian packages in a Debian Buster host.

**Comment by madrisan** [comment]
The [PR#85](https://github.com/madrisan/nagios-plugins-linux/pull/85) provides a way to get the current package version from the source code (see the new file `VERSION`).

**Comment by madrisan** [comment]
> grmpf - no - I don't understand, why a "make" is not generating binaries.... sorry. This is a problem in your build process. I would expect that make will generate the binaries somewhere.

`make` indeed generates the binaries in the folder `./plugins` as you can see executing the command:
```
make && find plugins/ -type f -executable
```

**Comment by madrisan** [comment]
Closed for inactivity.
