### ISSUE TITLE
[Bug] check_load and check_swap conflict with monitoring-plugins-basic

### ISSUE THREAD

**Issue by vincent-olivert-riera** [madrisan/nagios-plugins-linux#79]
The plugins `check_load` and `check_swap` are already provided by the `monitoring-plugin-basic` package in Debian. See:
https://packages.debian.org/buster/monitoring-plugins-basic

When installing the `.deb` file for `nagios-plugins-linux` it fails because it tries to overwrite those plugins.

**Comment by madrisan** [comment]
Thanks for your report. This is a known issue for the Debian package.
I'll try to ship the binaries in different sub-packages as already done for the .rpm format.

**Comment by vincent-olivert-riera** [comment]
@madrisan , what do you think about completely removing `check_load` and `check_swap` from this package? Since they are already included in `monitoring-plugins-basic` you don't have to maintain another copy here.

**Comment by madrisan** [comment]
These plugins can be used as an alternative to the official ones, so I'm afraid this is not an option.
